import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import Navbar from "@/components/ui/navbar";

const geistMonoHeading = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-heading",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "John Martin Demonteverde - Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarDefaultOpen =
    (await cookies()).get("sidebar_state")?.value === "true";

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "dark",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
        geistMonoHeading.variable,
      )}
    >
      <body className="min-h-full overflow-x-hidden flex flex-col">
        <SidebarProvider defaultOpen={sidebarDefaultOpen}>
          <AppSidebar />

          <main className="flex-1 min-w-0 w-full">
            <div className="sticky top-0 z-30 flex items-center gap-3 border-b border-[#2f333a] bg-[#07080a]/95 px-3 py-3 backdrop-blur sm:px-5 lg:px-7">
              <SidebarTrigger className="h-10 w-10 shrink-0 rounded-none border border-[#303642] bg-[#0b0d10] text-[#9aa7cf] hover:border-[#00ff66]/70 hover:bg-[#17191d] hover:text-[#00ff66]" />

              <div className="flex-1 min-w-0 overflow-visible">
                <Navbar />
              </div>
            </div>

            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
